export const AUTH_REQUEST="AUTH_REQUEST";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAIL="AUTH_FAIL";

export const LOAD_USER_REQUEST="LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL="LOAD_USER_FAIL";